# Generated by Django 2.2.1 on 2020-03-21 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_identification_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('defendant_name', models.CharField(blank=True, max_length=500)),
                ('defendant_address', models.CharField(blank=True, max_length=500)),
                ('crime_type', models.CharField(blank=True, max_length=500)),
                ('date_committed', models.DateField(blank=True)),
                ('time_committed', models.TimeField(blank=True)),
                ('crime_location', models.CharField(blank=True, max_length=500)),
                ('name_of_arresting_officer', models.CharField(blank=True, max_length=500)),
                ('date_of_arrest', models.DateField(blank=True)),
                ('time_of_arrest', models.TimeField(blank=True)),
                ('date_of_first_hearing', models.DateField(blank=True)),
                ('time_of_first_hearing', models.TimeField(blank=True)),
                ('date_of_completion_of_hearing', models.DateField(blank=True)),
                ('time_of_completion_of_hearing', models.TimeField(blank=True)),
                ('public_prosecutor', models.CharField(blank=True, max_length=500)),
                ('presiding_judge', models.CharField(blank=True, max_length=500)),
                ('summary_of_judgement', models.TextField(blank=True)),
                ('case_is_closed', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CaseProceeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceeding', models.TextField(blank=True)),
                ('date_of_proceeding', models.DateField(blank=True)),
                ('time_of_proceeding', models.TimeField(blank=True)),
                ('date_of_next_proceeding', models.DateField(blank=True)),
                ('time_of_next_proceeding', models.TimeField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jis_app.Case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseAdjournment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('date_adjourned_to', models.DateField(blank=True)),
                ('time_adjourned_to', models.TimeField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jis_app.Case')),
            ],
        ),
    ]
